export const defaultTestsData = [
  {
    name: 'Blood Count Test',
    children: [
      'RDW (Red Cell Distribution Width)',
      'Reticulocyte count',
      'Hemoglobin',
      'Packed Cell Volume (Haematocrit)',
      'RBC Count',
      'Total WBC',
      'Differential count',
      'Plateles Count',
      'MCV (Mean Corpuscular Volume)',
      'MCH (Mean Corpuscular Hemoglobin)',
      'MCHC (Mean Corpuscular Hemoglobin Concentration)',
    ],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
  {
    name: 'Malaria test',
    children: [
      'RBC Count',
      'Total WBC',
      'Differential count',
      'Plateles Count',
    ],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
  {
    name: 'Renal Function Test',
    children: ['Differential count', 'Plateles Count'],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
  {
    name: 'HIV Test',
    children: [],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
  {
    name: 'Hormonal Profile',
    children: [],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
  {
    name: 'Stool Analysis',
    children: [],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
  {
    name: 'Blood Sugar',
    children: ['Differential count', 'Plateles Count'],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
  {
    name: 'Glucose Metabolism Test',
    children: [],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
  {
    name: 'Covid Test',
    children: [],
    selectedChildren: [],
    expanded: false,
    status: 'pending',
  },
]
